#!/bin/sh 
	git rm     pages/adopt/commit.vue
	git rm     pages/adopt/form.vue
	git rm     pages/animal/.details.vue.baiduyun.uploading.cfg
	git rm     pages/animal/animalEdit/VideoPic.vue
	git rm     pages/animal/animalEdit/VideoUpload.vue
	git rm     pages/animal/animalEdit/edit.vue
	git rm     pages/animal/animalEdit/editFormItem.vue
	git rm     pages/animal/animalEdit/edit_bak.vue
	git rm     pages/animal/animalEdit/tempFromXC.vue
	git rm     pages/animal/cameraPotho.vue
	git rm     pages/animal/details.vue
	git rm     pages/animal/donate.vue
	git rm     pages/animal/share.vue
	git rm     pages/auth/@login.vue
	git rm     pages/auth/login.vue
	git rm     pages/components/breadcrumb/index.vue
	git rm     pages/components/fatherLogin/index.vue
	git rm     pages/organization/details.vue
	git rm     pages/organization/editForm.vue
	git rm     pages/organization/editFormItem.vue
	git rm     pages/organization/faqEdit.vue
	git rm     pages/organization/faqList.vue
	git rm     pages/organization/share.vue
